# Generated by Django 4.0.5 on 2022-06-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('biography', models.TextField(max_length=2000)),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='artists')),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('adress', models.TextField(max_length=1000)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('image', models.ImageField(null=True, upload_to='museums')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(null=True, upload_to='properties')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_museum.artist')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_museum.medium')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_museum.museum')),
            ],
        ),
    ]
